"""empty message

Revision ID: 2dbb373604e9
Revises: 90b56e393f2d
Create Date: 2023-04-20 08:48:35.525312

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '2dbb373604e9'
down_revision = '90b56e393f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('wallets', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('wallets', 'addresses')
    # ### end Alembic commands ###
