"""empty message

Revision ID: 90b56e393f2d
Revises: b2f34cb2352d
Create Date: 2023-04-20 08:24:25.647148

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '90b56e393f2d'
down_revision = 'b2f34cb2352d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('currency', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'currency')
    # ### end Alembic commands ###
