"""empty message

Revision ID: fb1c7cc20c97
Revises: 2dbb373604e9
Create Date: 2023-04-20 10:08:40.068322

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'fb1c7cc20c97'
down_revision = '2dbb373604e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('seed', sa.String(), nullable=False))
    op.add_column('wallets', sa.Column('mnemonic', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'mnemonic')
    op.drop_column('wallets', 'seed')
    # ### end Alembic commands ###
